package:
    name: mopper 
    version: {{ "1.0.0" }}

#source:
#    path: ./

source:
  #url: https://github.com/ACCESS-Hive/ACCESS-MOPPeR/archive/refs/tags/{{version}}.tar.gz
  git_url: https://github.com/ACCESS-Hive/ACCESS-MOPPeR.git
  git_rev: {{ "1.0.0" }} 
  git_depth: 1 # (Defaults to -1/not shallow)

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
    entry_points:
        - mop = mopper.mopper:mop_catch
        - mopdb = mopdb.mopdb:mopdb

requirements:
    host:
        - python
        - pip
        - pbr
    run:
        - python
        - click
        - cmor
        - xarray
        - numpy
        - dask
        - pyyaml
        - cftime
        - python-dateutil
test:
  source_files:
    - tests/testdata

about:
    home: https://github.com/ACCESS-Hive/ACCESS-MOPPeR
    license: Apache 2.0
    #license_file: LICENSE.txt
    summary: 'ACCESS-MOPPeR post-process ACCESS raw model output to ESGF data standards' 
