package:
    name: mopper 
    version: "{{ environ.get('GIT_DESCRIBE_TAG', '0.9') }}"

#source:
#    path: ./

source:
  #url: https://github.com/ACCESS-Hive/ACCESS-MOPPeR/archive/refs/tags/{{version}}.tar.gz
  git_url: https://github.com/ACCESS-Hive/ACCESS-MOPPeR.git
  git_tag: prerelease
  #git_rev: "{{ version }}" 
  #git_depth: 1 # (Defaults to -1/not shallow)
  #path: ../

build:
    number: 1
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
    entry_points:
        - mop = mopper.mopper:mop_catch
        - mopdb = mopdb.mopdb:mopdb

requirements:
    host:
        - python
        - pip
    run:
        - python
        - click
        - cmor
        - xarray
        - numpy
        - dask
        - pyyaml
        - cftime
        - python-dateutil

test:
  source_files:
    - tests/testdata/*
    - tests/testdata
  requires:
    - pytest
    - pyfakefs

about:
    home: https://github.com/ACCESS-Hive/ACCESS-MOPPeR
    license: Apache 2.0
    #license_file: LICENSE.txt
    summary: 'ACCESS-MOPPeR post-process ACCESS raw model output using CMOR and pre-defined data standards' 
