name: mopper-all-tests

#on: [push]
on: 
  push:
    branches:
      #- prerelease
      - class
  #pull_request:
  #  branches:
  #    - main
  #    - prerelease


jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda config --set solver classic
        conda env update --file conda/test-env.yaml --name base 
    - name: Lint with flake8
      run: |
        conda install -c conda-forge ruff 
        ruff check --output-format=github .
      continue-on-error: true
    # making sure we are testing installed package
    - name: Install package
      run: |
        pip install  -e .
    - name: Test with pytest
      run: |
        conda install pytest coverage codecov
        conda install -c conda-forge pyfakefs 
        conda run python -m pytest
        #conda run coverage run --source src -m py.test
   # - name: Upload to codecov 
   #   if: steps.build.outcome == 'success'
   #   run: |
   #     curl -Os https://uploader.codecov.io/latest/linux/codecov
   #     chmod +x codecov
   #     ./codecov

