name: mopper-all-tests

#on: [push]
on: 
  push:
    branches:
      #- prerelease
      - class
  #pull_request:
  #  branches:
  #    - main
  #    - prerelease


jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        activate-environment: testenv
        environment-file: conda/testenv.yaml
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    #- name: Add conda to system path
    #  run: |
    #    # $CONDA is an environment variable pointing to the root of the miniconda directory
    #    echo $CONDA/bin >> $GITHUB_PATH
    - name: Lint with ruff
      shell: bash -el {0}
      run: |
        ruff check --output-format=github .
      continue-on-error: true
     
    # making sure we are testing installed package
    - name: Install package
      shell: bash -el {0}
      run: |
        conda activate testenv
        pip install  -e .
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        conda run python -m pytest
        #conda run coverage run --source src -m py.test
   # - name: Upload to codecov 
   #   shell: bash -el {0}
   #   if: steps.build.outcome == 'success'
   #   run: |
   #     curl -Os https://uploader.codecov.io/latest/linux/codecov
   #     chmod +x codecov
   #     ./codecov

