name: mopper-all-tests

#on: [push]
on: 
  push:
    branches:
      #- prerelease
      - class
  #pull_request:
  #  branches:
  #    - main
  #    - prerelease


jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        auto-update-conda: true
        activate-environment: testenv
        environment-file: conda/testenv.yaml
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    #- name: Add conda to system path
    #  run: |
    #    # $CONDA is an environment variable pointing to the root of the miniconda directory
    #    echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        #conda config --set solver classic
        # this seems to slow it down!!!
        #conda env update --file conda/test-env.yaml --name testenv
        conda activate testenv
        conda list
    - name: Lint with ruff
      run: |
        #conda install -c conda-forge ruff  #--solver classic 
        source ~/miniconda/bin/activate testenv
        ruff check --output-format=github .
      continue-on-error: true
     
    # making sure we are testing installed package
    - name: Install package
      run: |
        source ~/miniconda/bin/activate testenv
        pip install  -e .
    - name: Test with pytest
      run: |
        #conda install pytest coverage codecov #--name testenv #--solver classic
        #conda install -c conda-forge pyfakefs #--name testenv
        source ~/miniconda/bin/activate testenv
        conda run python -m pytest
        #conda run coverage run --source src -m py.test
   # - name: Upload to codecov 
   #   if: steps.build.outcome == 'success'
   #   run: |
         source ~/miniconda/bin/activate testenv
   #     curl -Os https://uploader.codecov.io/latest/linux/codecov
   #     chmod +x codecov
   #     ./codecov

